function UseCtD001
Sele 0
Use CtD001 Index CtI00101, CtI00102              Alias Empresa
Return ''

function useCtD002
Sele 0
Use CTD002 Index CTI00201, CtI00202              Alias Conta
return ''

function useCtD003
Sele 0
Use CTD003 Index CTI00301                        Alias Historico
return ''

function useCtD004
Sele 0
Use CTD004 Index CTI00401, CtI00402, CtI00403    Alias Lancamento
return ''

Function UseCtD005
Sele 0
Use CtD005 Index CtI00501, CtI00502              Alias SaldoCt

function UseCtd007
Sele 0
Use CTD006 Index CTI00701                        Alias  Moedas
return ''

function useCtD009
Sele 0
Use CTD009 Index CTI00901                        Alias Arquivo
return ''

function useCtD012
Sele 0
Use CTD012 Index CTI01201                        Alias SaldoInter
return ''

function useCtD015
Sele 0
Use CTD015 Index CtI01501                        Alias Status
return ''

function useCtD017
Sele 0
Use CTD017                                       Alias SaldoBalanco
return ''

function useCtD019
Sele 0
Use CTD019                                       Alias Parametro
return ''

function useCtD020
Sele 0
Use CTD020  Index  Cti02001                      Alias SaldoApuracao
return ''
